from .bloom import BloomAWQForCausalLM
from .deepseek_v2 import DeepseekV2AWQForCausalLM
from .deepseek_v3 import DeepseekV3AWQForCausalLM
from .falcon import FalconAWQForCausalLM
from .gptj import GPTJAWQForCausalLM
from .gpt_bigcode import GptBigCodeAWQForCausalLM
from .gpt_neox import GPTNeoXAWQForCausalLM
from .internlm2 import InternLM2AWQForCausalLM
from .mpt import MptAWQForCausalLM
from .minicpm import MiniCPMAWQForCausalLM
from .minicpm3 import MiniCPM3AWQForCausalLM
from .opt import OptAWQForCausalLM
from .phi3_v import Phi3VAWQForCausalLM
from .qwen import QwenAWQForCausalLM
from .qwen2vl import Qwen2VLAWQForCausalLM